USE [master]
GO

/****** Object:  Database [SHOP]    Script Date: 5/14/2022 6:28:56 PM ******/
CREATE DATABASE [SHOP]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SHOP', FILENAME = N'/var/opt/mssql/data/SHOP.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SHOP_log', FILENAME = N'/var/opt/mssql/data/SHOP_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SHOP].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SHOP] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SHOP] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SHOP] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SHOP] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SHOP] SET ARITHABORT OFF 
GO

ALTER DATABASE [SHOP] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SHOP] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SHOP] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SHOP] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SHOP] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SHOP] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SHOP] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SHOP] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SHOP] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SHOP] SET  DISABLE_BROKER 
GO

ALTER DATABASE [SHOP] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SHOP] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SHOP] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SHOP] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SHOP] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SHOP] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SHOP] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SHOP] SET RECOVERY FULL 
GO

ALTER DATABASE [SHOP] SET  MULTI_USER 
GO

ALTER DATABASE [SHOP] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SHOP] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SHOP] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SHOP] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [SHOP] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [SHOP] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [SHOP] SET QUERY_STORE = OFF
GO

ALTER DATABASE [SHOP] SET  READ_WRITE 
GO


